(function(r,n){typeof exports=="object"&&typeof module<"u"?n(exports,require("react"),require("react-dom")):typeof define=="function"&&define.amd?define(["exports","react","react-dom"],n):(r=typeof globalThis<"u"?globalThis:r||self,n(r.MyWidget={},r.React,r.ReactDOM))})(this,function(r,n,w){"use strict";function E(e){return e&&e.__esModule&&Object.prototype.hasOwnProperty.call(e,"default")?e.default:e}var u={},R;function M(){if(R)return u;R=1;var e=w;return u.createRoot=e.createRoot,u.hydrateRoot=e.hydrateRoot,u}var T=M();const S=E(T);var p={exports:{}},c={};/**
 * @license React
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var _;function W(){if(_)return c;_=1;var e=n,d=Symbol.for("react.element"),i=Symbol.for("react.fragment"),a=Object.prototype.hasOwnProperty,h=e.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,P={key:!0,ref:!0,__self:!0,__source:!0};function v(f,t,O){var o,l={},y=null,g=null;O!==void 0&&(y=""+O),t.key!==void 0&&(y=""+t.key),t.ref!==void 0&&(g=t.ref);for(o in t)a.call(t,o)&&!P.hasOwnProperty(o)&&(l[o]=t[o]);if(f&&f.defaultProps)for(o in t=f.defaultProps,t)l[o]===void 0&&(l[o]=t[o]);return{$$typeof:d,type:f,key:y,ref:g,props:l,_owner:h.current}}return c.Fragment=i,c.jsx=v,c.jsxs=v,c}var x;function q(){return x||(x=1,p.exports=W()),p.exports}var s=q();const m=()=>{const[e,d]=n.useState([]);return n.useEffect(()=>{(async()=>{try{const h=await(await fetch("https://jsonplaceholder.typicode.com/todos")).json();d(h)}catch(a){console.error("Error fetching todos:",a)}})()},[]),s.jsxs("div",{children:[s.jsx("h2",{children:"My React Widget"}),s.jsx("p",{children:"Todos from JSONPlaceholder:"}),s.jsx("ul",{children:e.length===0?s.jsx("li",{children:"Loading..."}):e.slice(0,10).map(i=>s.jsxs("li",{style:{textDecoration:i.completed?"line-through":"none"},children:[i.title," ",i.completed?"✅":""]},i.id))})]})};function j(e){if(!e){console.error("MyWidget.mount: container is required");return}S.createRoot(e).render(n.createElement(m))}window!=="undefined"&&(window.MyWidget=m,window.MyWidget.mount=j),r.MyWidget=m,r.mount=j,Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});
